# List vs numpy

In [6]:
a = [2,3,4,5,6,7]
for i in range(len(a)): 
    a[i] = a[i] + 2
print(a)

[4, 5, 6, 7, 8, 9]


# Clener Code

In [9]:
import numpy as np
a = np.array([2,3,4,5,6,7,8])
print(a + 2)


[ 4  5  6  7  8  9 10]


# Efficent code

In [14]:
a_list = range(100000)
%timeit [element + 2 for element in a_list]

7.42 ms ± 502 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# In numpy

In [15]:
a_array = np.array(a_list)
%timeit a_array +2

84.7 μs ± 576 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# Other benefits

In [17]:
import numpy as np
L1 = np.array([[1,2,3],
               [4,5,6]]) #2D array 'L1'(2x3)
L2 = np.array([[7,8,9]])# 2D array 'L2'

#Elementwise sum operation
print(L1+L2)

[[ 8 10 12]
 [11 13 15]]


In [20]:
# 3) Define a matrix (2x3)
matrix = np.array([[1,2,3],
                   [4,5,6]])

Vector = np.array([7,8,9]) # (3x1)

# perform matrix-vector multiplication for Neural Nets
result = matrix @ Vector
print(result)

[ 50 122]


# Creating numpy array

In [23]:
import numpy as np

# Creating a numpy from a list
l = [1,2,3,4,5,6]
arr = np.array(l) # output th array
print(arr)

[1 2 3 4 5 6]


In [24]:
import numpy as np


seq = range(1,100,10)
print("Native Python range:", list(seq))


seq_arr = np.arange(1,100,10)
print("Seq with stop 10:", seq_arr)


seq_arr2 = np.arange(1,100,10.5)
print("Seq with stop 10.5:", seq_arr2)

Native Python range: [1, 11, 21, 31, 41, 51, 61, 71, 81, 91]
Seq with stop 10: [ 1 11 21 31 41 51 61 71 81 91]
Seq with stop 10.5: [ 1.  11.5 22.  32.5 43.  53.5 64.  74.5 85.  95.5]


# Reading N-Dimensional Aarray

In [35]:
import numpy as np

arr1 = np.array([32, 95, 11, 67, 78, 89])
arr2 = np.array([[1,2,3],
                 [4,5,6]])
print(len(arr1))
print(arr1.shape)
print(len(arr2))
print(arr2.shape)

6
(6,)
2
(2, 3)


# Indexing and Slicing in numpy

In [36]:
# Accessing the 4th emement(index3)from 'arr'-[34,45,56,67,78,89]
# output the 4th element of array 'arr1'
arr1[3]

np.int64(67)

In [40]:
import numpy as np
arr1 = np.array([34,45,56,67,78,89])

print(arr1[2:5])

[56 67 78]


In [41]:
# 2-D array-[[1,2,3]
#[4,5,6]].
# Accessing the second row of array (index1)
arr2[1,1]


np.int64(5)

In [43]:
# Accessing 2nd of first row-[[1,2,3],[4,5,6]]
print(arr2[0,1])

2


In [44]:
# Accessing the Second and third elements of first row index 1to2 [[1,2,3],[4,5,6]]
print(arr2[0,1:3])

[2 3]


# UPdating

In [45]:
# correctly assigning an integer value to the second element (index 1)
arr1[1] = 12 # works because 12 is an integer

# printing the update array
print(arr1)

[34 12 56 67 78 89]


# Operation of numpy

In [51]:
salaries = np.array([10,15,20,25,30])
# Calculation the mean of salary value
mean_salary = np.mean(salaries) # Calculate the mean salary
print(f"mean salary: {mean_salary} LPA")

mean salary: 20.0 LPA


In [52]:
median_salary = np.median (salaries)# Calculate the median salary
print(f"median salary salary:{median_salary} LPA")

median salary salary:20.0 LPA


In [53]:
# finding profduct of all elements of the array
print(np.prod(salaries))

2250000


In [57]:
#Returns the sorted unique elements from the 'salaries' array
salaries2 =np.array([10,15,20,25,30,15,20])
np.unique(salaries2, return_counts=True)

(array([10, 15, 20, 25, 30]), array([1, 2, 2, 1, 1]))

# Multidimension-Arrays

In [60]:
# Creating a 3-D Numpy array
# shape: (2 blocks, 2 rows, 3 columns)
t1 = np.array([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [10,11,12]]
])

print(t1.shape) 
print(len(t1))  
print(t1.size)

(2, 2, 3)
2
12


In [63]:
# Accessing the first 2D block
print("First block:\n", t1[0])

First block:
 [[1 2 3]
 [4 5 6]]


In [64]:
# Accessing the second row of the first 2D block (axis 0=0, axis 1=1)
print("First Block, second row:", t1[0,1])

First Block, second row: [4 5 6]


In [65]:
# Accessing the second element of the second row in the first 2D block
# (axis 0=0, axis 1=1, axis 2=1)
print("First Block, Second row, Second Column:", t1[0,1,1])

First Block, Second row, Second Column: 5


In [66]:
t1 = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ])

print(t1.mean())
print(t1.shape)
print(t1.mean(axis=2))
print(t1.mean(axis=2).shape)

6.5
(2, 2, 3)
[[ 2.  5.]
 [ 8. 11.]]
(2, 2)


In [67]:
t1.sum(axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [68]:
t1.sum(axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

# Fancy indexing

In [72]:
#creating a Numpy array of student scores
Score1 =np.array([85,92,78])
#check which number are greater than82
Score1>82

array([ True,  True, False])

In [76]:
# Apply multiple conditions: Greater than 80 and less than 93
np.where((Scores1 > 80) & (Scores1 < 93))

(array([0, 1]),)

In [78]:
np.all(Scores1<=78)

np.False_

In [79]:
# Define a Numpy array
a = np.array([1, 2, 3, 4, 5, 6])

# Find indices where the condition a > 2 is True
np.where(a > 2)

(array([2, 3, 4, 5]),)

In [81]:
a[np.where(a > 2)]


array([3, 4, 5, 6])

# Matrix Multiplication

In [82]:
a = np.array([[1,2,3], [4,5,6]])

x = np.array([[7,8,9,10], [11,12,13,14], [15,16,17,18]])

ax = np.dot(a,x) # ya a @ x 
print("Result of matrix multiplication (a*x):\n", ax)

Result of matrix multiplication (a*x):
 [[ 74  80  86  92]
 [173 188 203 218]]


In [83]:
import numpy as np

Forecast = np.array([
    [100, 200, 150], # Forecast 1
    [90, 250, 120]   # Forecast 2
]) # Shape (2,3)

Price = np.array([
    [10, 12, 11], # Product A Price 3 din ka
    [9, 7, 7],    # Product B
    [15, 10, 15]  # Product C
]) # Shape (3,3)

Revenue = np.dot(Forecast, Price) # (2,3) x (3,3) = (2,3)
print(Revenue)

[[5050 4100 4750]
 [4950 4030 4540]]


# Broadcsting in numpy

In [84]:

delivery_cost = np.array([100, 150, 120])

total_with_delivery = Revenue + delivery_cost

print("\nDelivery cost per day:\n", delivery_cost)
print("\nRevenue after adding delivery cost (broadcasted):\n", total_with_delivery)


Delivery cost per day:
 [100 150 120]

Revenue after adding delivery cost (broadcasted):
 [[5150 4250 4870]
 [5050 4180 4660]]


# Miscellaneous Methods

In [85]:
Current_year = np.array([[7000, 8000],
                         [9000, 10000]]) 
Previous_year = np.array([[65000, 70000],
                          [80000, 90000]]) 

all_years = np.concatenate([Current_year, Previous_year], axis=0)
print(all_years)

[[ 7000  8000]
 [ 9000 10000]
 [65000 70000]
 [80000 90000]]
